server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm
    username: sa
    password: sa
  jpa:
    hibernate.ddl-auto: update
stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}

