services:
  # -------- STATISTICS --------
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: ${STATISTICS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STATISTICS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STATISTICS_POSTGRES_DB}
    ports:
      - "${STATISTICS_POSTGRES_PORT}:5432"  # хост:контейнер
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STATISTICS_POSTGRES_USER} -d ${STATISTICS_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  stats-server:
    build: ./statistics-service/statistics-server
    image: statistics_service:latest
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: ${STATISTICS_SPRING_DATASOURCE_URL}   # jdbc:postgresql://stats-db:5432/statistics
      SPRING_DATASOURCE_USERNAME: ${STATISTICS_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${STATISTICS_POSTGRES_PASSWORD}
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    restart: unless-stopped

  # -------- MAIN (EWM) --------
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: ${EWM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EWM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EWM_POSTGRES_DB}
    ports:
      - "${EWM_POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${EWM_POSTGRES_USER} -d ${EWM_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  ewm-service:
    build: ./ewm-service
    image: ewm_service:latest
    container_name: ewm-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/${EWM_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${EWM_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${EWM_POSTGRES_PASSWORD}
      STATS_SERVER_URL: http://stats-server:9090
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped
