services:

  stats-server:
    build: statistics-service/statistics-server/
    image: statistics_service:latest
    container_name: service
    environment:
      - SPRING_DATASOURCE_URL=${STATISTICS_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${STATISTICS_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${STATISTICS_POSTGRES_PASSWORD}

    restart: unless-stopped

    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${STATISTICS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STATISTICS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STATISTICS_POSTGRES_DB}
    ports:
      - "${STATISTICS_POSTGRES_PORT}:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${STATISTICS_POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

# todo убрал, иначе для отлдадки порт занимает. Вернем при сборке
  #ewm-service:
  #  build: ewm-service/
  #  image: ewm_service:latest
  #  ports:
  #    - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${EWM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EWM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EWM_POSTGRES_DB}
    ports:
      - "${EWM_POSTGRES_PORT}:5432"