services:
  stats-server:
    build: statistics-service/statistics-server/
    image: statistics-service:latest
    container_name: service
    ports:
      - "9090:9090"
#    hostname: localhost
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa

    restart: unless-stopped

    depends_on:
      stats-db:
        condition: service_healthy


  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statistics_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service/
    image: ewm-service:latest
    ports:
      - "8080:8080"

  ewm-db:
      image: postgres:16.1
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_DB=jdbc:postgresql://stats-db:5432/statistics_db
        - POSTGRES_USER=_sa
        - POSTGRES_PASSWORD=_sa
      healthcheck:
        test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
        timeout: 5s
        interval: 5s
        retries: 10
